[versions]
android-plugin = "8.2.2"
androidx-annotation = "1.7.1"
publish-plugin = "1.3.0"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-plugin" }
publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
