[versions]
android-plugin = "8.4.1"
androidx-annotation = "1.8.0"
publish-plugin = "2.0.0"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidx-annotation" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-plugin" }
publish-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish-plugin" }
